version: "2"

services:
  booker:
    build:
      context: .
      dockerfile: Dockerfile
    image: books
    ports:
      - "43306:43306"
    volumes:
      - .:/go/src/books
    working_dir: /go/src/books
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=books
      - MYSQL_USER=demouser
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
