version: "2"

services:
  books:
    build:
      context: .
      dockerfile: Dockerfile
    image: books
    ports:
      - "43306:43306"
    volumes:
      - .:/go/src/books
    working_dir: /go/src/books
    # command: go test -v
