version: "2"

services:
  books:
    build:
      context: .
      dockerfile: Dockerfile
    image: books
    ports:
      - "43306:43306"
    volumes:
      - .:/go/src/books
    working_dir: /go/src/books
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    # command: go test -v
