CREATE DATABASE IF NOT EXISTS booksdb;
use booksdb;
CREATE TABLE IF NOT EXISTS books
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) DEFAULT NULL,
    author VARCHAR(100) DEFAULT NULL,
    publisher VARCHAR(100) DEFAULT NULL,
    publishdate VARCHAR(100) DEFAULT NULL,
    rating INT DEFAULT 0,
    status INT DEFAULT 0
);
